name: Vercel Envs Push
description: Push variables in a .env format to your Vercel project
branding:
  icon: triangle
  color: gray-dark
inputs:
  project:
    description: Vercel project name
    required: true
  team_id:
    description: The unique ID of your Vercel team
    required: true
  token:
    description: Vercel token
    required: true
  environments:
    description: Environments to target variables. If multiple, separate by comma, for example "development,preview"
    required: false
    default: development
  env_type:
    description: The variable type. Allowed values are 'system', 'encrypted', 'plain' or 'secret'.
    required: true
    default: encrypted
  env_file:
    description: The path to your env file
    required: false
    default: .env

runs:
  using: node16
  main: index.js
